### ISSUE TITLE
"Update the CRL" handler run everytime

### ISSUE THREAD

**Issue by arbabnazar** [Logan2211/ansible-openvpn#11]
@Logan2211 want to know about this [handler](https://github.com/Logan2211/ansible-openvpn/blob/master/tasks/openvpn_keys_ca.yml#L43) which execute everytime you run the playbook becuase `touch` parameter of `file` module change the create time of the file which trigger the handler, is it intentional or by mistake? will it make any impact as the content of the `ca.crl` changes.

**Comment by logan2211** [comment]
Yep.. good catch. I think you're right that the `touch` will return a changed result every time and trigger the handler. I don't think it will break anything, just result in the crl being regenerated unnecessarily.

Maybe the `touch` task should be moved to a handler and they should be notified by a `stat` that is changed when the file does not exist.
